language: python
dist: xenial
python:
    - 2.7
    - 3.6
    - 3.7
before_install:
    - pip install -U setuptools pip
    - pip install -U coverage coveralls zope.testrunner
install:
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src --all -v1
notifications:
    email: false
after_success:
    - coveralls
cache:
  pip: true
